name: deploy backend

on:
  push:
    branches: [main]
    paths:
      - 'packages/server/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
          
  deploy:
    needs: build
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: '.'
          target: '/home/ubuntu/instagram-clone'
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo $PATH
            cd /home/ubuntu/instagram-clone
            rm -rf packages/web
            yarn
            cd packages/server
            yarn build

